version: '2'

services:
    php:
      build:
        context: php7-fpm
#      image: php:7-fpm
      volumes:
        - ./code:/code
    web:
      image: nginx:latest
      ports:
        - "80:80"
      volumes:
        - ./logs/nginx/:/var/log/nginx
        - ./site.conf:/etc/nginx/conf.d/site.conf
      volumes_from:
        - php
    db:
      image: mysql:5.7
#      volumes:
#       - "./dbdata:/var/lib/mysql"
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: docker_test
        MYSQL_USER: docker_test
        MYSQL_PASSWORD: docker_test
      ports:
        - "13306:3306"

    memcached:
      hostname: memcached
      image: memcached
      environment:
        - MEMCACHED_MEMORY_LIMIT=128

    browser:
      hostname: browser
      image: selenium/standalone-chrome
      links:
        - web
      ports:
        - "4444:4444"